/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class ArrayStoreAll {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ArrayStoreAll(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ArrayStoreAll obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_ArrayStoreAll(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArrayStoreAll(ArrayType type, Expr expr) {
    this(CVC4JNI.new_ArrayStoreAll__SWIG_0(ArrayType.getCPtr(type), type, Expr.getCPtr(expr), expr), true);
  }

  public ArrayStoreAll(ArrayStoreAll other) {
    this(CVC4JNI.new_ArrayStoreAll__SWIG_1(ArrayStoreAll.getCPtr(other), other), true);
  }

  public ArrayType getType() {
    return new ArrayType(CVC4JNI.ArrayStoreAll_getType(swigCPtr, this), false);
  }

  public Expr getExpr() {
    return new Expr(CVC4JNI.ArrayStoreAll_getExpr(swigCPtr, this), false);
  }

  public boolean equals(ArrayStoreAll asa) {
    return CVC4JNI.ArrayStoreAll_equals(swigCPtr, this, ArrayStoreAll.getCPtr(asa), asa);
  }

  public boolean less(ArrayStoreAll asa) {
    return CVC4JNI.ArrayStoreAll_less(swigCPtr, this, ArrayStoreAll.getCPtr(asa), asa);
  }

  public boolean lessEqual(ArrayStoreAll asa) {
    return CVC4JNI.ArrayStoreAll_lessEqual(swigCPtr, this, ArrayStoreAll.getCPtr(asa), asa);
  }

  public boolean greater(ArrayStoreAll asa) {
    return CVC4JNI.ArrayStoreAll_greater(swigCPtr, this, ArrayStoreAll.getCPtr(asa), asa);
  }

  public boolean greaterEqual(ArrayStoreAll asa) {
    return CVC4JNI.ArrayStoreAll_greaterEqual(swigCPtr, this, ArrayStoreAll.getCPtr(asa), asa);
  }

}
