/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class ArrayStoreAllHashFunction {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ArrayStoreAllHashFunction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ArrayStoreAllHashFunction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_ArrayStoreAllHashFunction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long apply(ArrayStoreAll asa) {
    return CVC4JNI.ArrayStoreAllHashFunction_apply(swigCPtr, this, ArrayStoreAll.getCPtr(asa), asa);
  }

  public ArrayStoreAllHashFunction() {
    this(CVC4JNI.new_ArrayStoreAllHashFunction(), true);
  }

}
