/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class BitVectorBitOf {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BitVectorBitOf(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BitVectorBitOf obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_BitVectorBitOf(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBitIndex(long value) {
    CVC4JNI.BitVectorBitOf_bitIndex_set(swigCPtr, this, value);
  }

  public long getBitIndex() {
    return CVC4JNI.BitVectorBitOf_bitIndex_get(swigCPtr, this);
  }

  public BitVectorBitOf(long i) {
    this(CVC4JNI.new_BitVectorBitOf(i), true);
  }

  public boolean equals(BitVectorBitOf other) {
    return CVC4JNI.BitVectorBitOf_equals(swigCPtr, this, BitVectorBitOf.getCPtr(other), other);
  }

}
