/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class BitVectorRotateRight {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BitVectorRotateRight(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BitVectorRotateRight obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_BitVectorRotateRight(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRotateRightAmount(long value) {
    CVC4JNI.BitVectorRotateRight_rotateRightAmount_set(swigCPtr, this, value);
  }

  public long getRotateRightAmount() {
    return CVC4JNI.BitVectorRotateRight_rotateRightAmount_get(swigCPtr, this);
  }

  public BitVectorRotateRight(long rotateRightAmount) {
    this(CVC4JNI.new_BitVectorRotateRight(rotateRightAmount), true);
  }

  public long toUnsigned() {
    return CVC4JNI.BitVectorRotateRight_toUnsigned(swigCPtr, this);
  }

}
