/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class BitVectorType extends Type {
  private transient long swigCPtr;

  protected BitVectorType(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.BitVectorType_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BitVectorType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_BitVectorType(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BitVectorType(Type type) {
    this(CVC4JNI.new_BitVectorType__SWIG_0(Type.getCPtr(type), type), true);
  }

  public BitVectorType() {
    this(CVC4JNI.new_BitVectorType__SWIG_1(), true);
  }

  public long getSize() {
    return CVC4JNI.BitVectorType_getSize(swigCPtr, this);
  }

}
