/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class BitVectorZeroExtend {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BitVectorZeroExtend(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BitVectorZeroExtend obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_BitVectorZeroExtend(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setZeroExtendAmount(long value) {
    CVC4JNI.BitVectorZeroExtend_zeroExtendAmount_set(swigCPtr, this, value);
  }

  public long getZeroExtendAmount() {
    return CVC4JNI.BitVectorZeroExtend_zeroExtendAmount_get(swigCPtr, this);
  }

  public BitVectorZeroExtend(long zeroExtendAmount) {
    this(CVC4JNI.new_BitVectorZeroExtend(zeroExtendAmount), true);
  }

  public long toUnsigned() {
    return CVC4JNI.BitVectorZeroExtend_toUnsigned(swigCPtr, this);
  }

}
