/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class BooleanType extends Type {
  private transient long swigCPtr;

  protected BooleanType(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.BooleanType_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BooleanType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_BooleanType(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BooleanType(Type type) {
    this(CVC4JNI.new_BooleanType__SWIG_0(Type.getCPtr(type), type), true);
  }

  public BooleanType() {
    this(CVC4JNI.new_BooleanType__SWIG_1(), true);
  }

}
