/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class Command {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Command(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Command obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_Command(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void invoke(SmtEngine smtEngine) {
    CVC4JNI.Command_invoke__SWIG_0(swigCPtr, this, SmtEngine.getCPtr(smtEngine), smtEngine);
  }

  public void invoke(SmtEngine smtEngine, java.io.OutputStream out) {
    edu.nyu.acsys.CVC4.JavaOutputStreamAdapter tempout = new edu.nyu.acsys.CVC4.JavaOutputStreamAdapter();
    try {
      CVC4JNI.Command_invoke__SWIG_1(swigCPtr, this, SmtEngine.getCPtr(smtEngine), smtEngine, edu.nyu.acsys.CVC4.JavaOutputStreamAdapter.getCPtr(tempout));
    } finally {
    new java.io.PrintStream(out).print(tempout.toString());
    }
  }

  public void toStream(java.io.OutputStream out, int toDepth, boolean types, long dag, OutputLanguage language) {
    edu.nyu.acsys.CVC4.JavaOutputStreamAdapter tempout = new edu.nyu.acsys.CVC4.JavaOutputStreamAdapter();
    try {
      CVC4JNI.Command_toStream__SWIG_0(swigCPtr, this, edu.nyu.acsys.CVC4.JavaOutputStreamAdapter.getCPtr(tempout), toDepth, types, dag, language.swigValue());
    } finally {
    new java.io.PrintStream(out).print(tempout.toString());
    }
  }

  public void toStream(java.io.OutputStream out, int toDepth, boolean types, long dag) {
    edu.nyu.acsys.CVC4.JavaOutputStreamAdapter tempout = new edu.nyu.acsys.CVC4.JavaOutputStreamAdapter();
    try {
      CVC4JNI.Command_toStream__SWIG_1(swigCPtr, this, edu.nyu.acsys.CVC4.JavaOutputStreamAdapter.getCPtr(tempout), toDepth, types, dag);
    } finally {
    new java.io.PrintStream(out).print(tempout.toString());
    }
  }

  public void toStream(java.io.OutputStream out, int toDepth, boolean types) {
    edu.nyu.acsys.CVC4.JavaOutputStreamAdapter tempout = new edu.nyu.acsys.CVC4.JavaOutputStreamAdapter();
    try {
      CVC4JNI.Command_toStream__SWIG_2(swigCPtr, this, edu.nyu.acsys.CVC4.JavaOutputStreamAdapter.getCPtr(tempout), toDepth, types);
    } finally {
    new java.io.PrintStream(out).print(tempout.toString());
    }
  }

  public void toStream(java.io.OutputStream out, int toDepth) {
    edu.nyu.acsys.CVC4.JavaOutputStreamAdapter tempout = new edu.nyu.acsys.CVC4.JavaOutputStreamAdapter();
    try {
      CVC4JNI.Command_toStream__SWIG_3(swigCPtr, this, edu.nyu.acsys.CVC4.JavaOutputStreamAdapter.getCPtr(tempout), toDepth);
    } finally {
    new java.io.PrintStream(out).print(tempout.toString());
    }
  }

  public void toStream(java.io.OutputStream out) {
    edu.nyu.acsys.CVC4.JavaOutputStreamAdapter tempout = new edu.nyu.acsys.CVC4.JavaOutputStreamAdapter();
    try {
      CVC4JNI.Command_toStream__SWIG_4(swigCPtr, this, edu.nyu.acsys.CVC4.JavaOutputStreamAdapter.getCPtr(tempout));
    } finally {
    new java.io.PrintStream(out).print(tempout.toString());
    }
  }

  public String toString() {
    return CVC4JNI.Command_toString(swigCPtr, this);
  }

  public String getCommandName() {
    return CVC4JNI.Command_getCommandName(swigCPtr, this);
  }

  public void setMuted(boolean muted) {
    CVC4JNI.Command_setMuted(swigCPtr, this, muted);
  }

  public boolean isMuted() {
    return CVC4JNI.Command_isMuted(swigCPtr, this);
  }

  public boolean ok() {
    return CVC4JNI.Command_ok(swigCPtr, this);
  }

  public boolean fail() {
    return CVC4JNI.Command_fail(swigCPtr, this);
  }

  public boolean interrupted() {
    return CVC4JNI.Command_interrupted(swigCPtr, this);
  }

  public CommandStatus getCommandStatus() {
    long cPtr = CVC4JNI.Command_getCommandStatus(swigCPtr, this);
    return (cPtr == 0) ? null : new CommandStatus(cPtr, false);
  }

  public void printResult(java.io.OutputStream out, long verbosity) {
    edu.nyu.acsys.CVC4.JavaOutputStreamAdapter tempout = new edu.nyu.acsys.CVC4.JavaOutputStreamAdapter();
    try {
      CVC4JNI.Command_printResult__SWIG_0(swigCPtr, this, edu.nyu.acsys.CVC4.JavaOutputStreamAdapter.getCPtr(tempout), verbosity);
    } finally {
    new java.io.PrintStream(out).print(tempout.toString());
    }
  }

  public void printResult(java.io.OutputStream out) {
    edu.nyu.acsys.CVC4.JavaOutputStreamAdapter tempout = new edu.nyu.acsys.CVC4.JavaOutputStreamAdapter();
    try {
      CVC4JNI.Command_printResult__SWIG_1(swigCPtr, this, edu.nyu.acsys.CVC4.JavaOutputStreamAdapter.getCPtr(tempout));
    } finally {
    new java.io.PrintStream(out).print(tempout.toString());
    }
  }

  public Command exportTo(ExprManager exprManager, ExprManagerMapCollection variableMap) {
    long cPtr = CVC4JNI.Command_exportTo(swigCPtr, this, ExprManager.getCPtr(exprManager), exprManager, ExprManagerMapCollection.getCPtr(variableMap), variableMap);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

  public Command clone() {
    long cPtr = CVC4JNI.Command_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

}
