/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class CommandSuccess extends CommandStatus {
  private transient long swigCPtr;

  protected CommandSuccess(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.CommandSuccess_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CommandSuccess obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_CommandSuccess(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static CommandSuccess instance() {
    long cPtr = CVC4JNI.CommandSuccess_instance();
    return (cPtr == 0) ? null : new CommandSuccess(cPtr, false);
  }

  public CommandStatus clone() {
    return new CommandStatus(CVC4JNI.CommandSuccess_clone(swigCPtr, this), false);
  }

  public CommandSuccess() {
    this(CVC4JNI.new_CommandSuccess(), true);
  }

}
