/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class CommandSequence extends Command implements Iterable<Command> {
  private transient long swigCPtr;

  protected CommandSequence(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.CommandSequence_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CommandSequence obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_CommandSequence(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CommandSequence() {
    this(CVC4JNI.new_CommandSequence(), true);
  }

  public void addCommand(Command cmd) {
    CVC4JNI.CommandSequence_addCommand(swigCPtr, this, Command.getCPtr(cmd), cmd);
  }

  public void clear() {
    CVC4JNI.CommandSequence_clear(swigCPtr, this);
  }

  public void invoke(SmtEngine smtEngine) {
    CVC4JNI.CommandSequence_invoke__SWIG_0(swigCPtr, this, SmtEngine.getCPtr(smtEngine), smtEngine);
  }

  public void invoke(SmtEngine smtEngine, java.io.OutputStream out) {
    edu.nyu.acsys.CVC4.JavaOutputStreamAdapter tempout = new edu.nyu.acsys.CVC4.JavaOutputStreamAdapter();
    try {
      CVC4JNI.CommandSequence_invoke__SWIG_1(swigCPtr, this, SmtEngine.getCPtr(smtEngine), smtEngine, edu.nyu.acsys.CVC4.JavaOutputStreamAdapter.getCPtr(tempout));
    } finally {
    new java.io.PrintStream(out).print(tempout.toString());
    }
  }

  public Command exportTo(ExprManager exprManager, ExprManagerMapCollection variableMap) {
    long cPtr = CVC4JNI.CommandSequence_exportTo(swigCPtr, this, ExprManager.getCPtr(exprManager), exprManager, ExprManagerMapCollection.getCPtr(variableMap), variableMap);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

  public Command clone() {
    long cPtr = CVC4JNI.CommandSequence_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

  public String getCommandName() {
    return CVC4JNI.CommandSequence_getCommandName(swigCPtr, this);
  }

  public JavaIteratorAdapter_CommandSequence iterator() {
    return new JavaIteratorAdapter_CommandSequence(CVC4JNI.CommandSequence_iterator(swigCPtr, this), true);
  }

}
