/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class CVC4IllegalArgumentException extends Exception {
  private transient long swigCPtr;

  protected CVC4IllegalArgumentException(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.CVC4IllegalArgumentException_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CVC4IllegalArgumentException obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_CVC4IllegalArgumentException(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CVC4IllegalArgumentException(String condStr, String argDesc, String function, String tail) {
    this(CVC4JNI.new_CVC4IllegalArgumentException__SWIG_1(condStr, argDesc, function, tail), true);
  }

  public CVC4IllegalArgumentException(String condStr, String argDesc, String function) {
    this(CVC4JNI.new_CVC4IllegalArgumentException__SWIG_2(condStr, argDesc, function), true);
  }

  public static String formatVariadic() {
    return CVC4JNI.CVC4IllegalArgumentException_formatVariadic__SWIG_0();
  }

  public static String formatVariadic(String format) {
    return CVC4JNI.CVC4IllegalArgumentException_formatVariadic__SWIG_1(format);
  }

}
