/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class CVC4StringHashFunction {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CVC4StringHashFunction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CVC4StringHashFunction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_CVC4StringHashFunction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long apply(CVC4String s) {
    return CVC4JNI.CVC4StringHashFunction_apply(swigCPtr, this, CVC4String.getCPtr(s), s);
  }

  public CVC4StringHashFunction() {
    this(CVC4JNI.new_CVC4StringHashFunction(), true);
  }

}
