/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class DatatypeConstructor implements Iterable<DatatypeConstructorArg> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DatatypeConstructor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DatatypeConstructor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_DatatypeConstructor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DatatypeConstructor(String name) {
    this(CVC4JNI.new_DatatypeConstructor__SWIG_0(name), true);
  }

  public DatatypeConstructor(String name, String tester, long weight) {
    this(CVC4JNI.new_DatatypeConstructor__SWIG_1(name, tester, weight), true);
  }

  public DatatypeConstructor(String name, String tester) {
    this(CVC4JNI.new_DatatypeConstructor__SWIG_2(name, tester), true);
  }

  public void addArg(String selectorName, Type selectorType) {
    CVC4JNI.DatatypeConstructor_addArg__SWIG_0(swigCPtr, this, selectorName, Type.getCPtr(selectorType), selectorType);
  }

  public void addArg(String selectorName, DatatypeUnresolvedType selectorType) {
    CVC4JNI.DatatypeConstructor_addArg__SWIG_1(swigCPtr, this, selectorName, DatatypeUnresolvedType.getCPtr(selectorType), selectorType);
  }

  public void addArg(String selectorName, DatatypeSelfType arg1) {
    CVC4JNI.DatatypeConstructor_addArg__SWIG_2(swigCPtr, this, selectorName, DatatypeSelfType.getCPtr(arg1), arg1);
  }

  public String getName() {
    return CVC4JNI.DatatypeConstructor_getName(swigCPtr, this);
  }

  public Expr getConstructor() {
    return new Expr(CVC4JNI.DatatypeConstructor_getConstructor(swigCPtr, this), true);
  }

  public Expr getTester() {
    return new Expr(CVC4JNI.DatatypeConstructor_getTester(swigCPtr, this), true);
  }

  public Expr getSygusOp() {
    return new Expr(CVC4JNI.DatatypeConstructor_getSygusOp(swigCPtr, this), true);
  }

  public boolean isSygusIdFunc() {
    return CVC4JNI.DatatypeConstructor_isSygusIdFunc(swigCPtr, this);
  }

  public SWIGTYPE_p_std__shared_ptrT_CVC4__SygusPrintCallback_t getSygusPrintCallback() {
    return new SWIGTYPE_p_std__shared_ptrT_CVC4__SygusPrintCallback_t(CVC4JNI.DatatypeConstructor_getSygusPrintCallback(swigCPtr, this), true);
  }

  public long getWeight() {
    return CVC4JNI.DatatypeConstructor_getWeight(swigCPtr, this);
  }

  public String getTesterName() {
    return CVC4JNI.DatatypeConstructor_getTesterName(swigCPtr, this);
  }

  public long getNumArgs() {
    return CVC4JNI.DatatypeConstructor_getNumArgs(swigCPtr, this);
  }

  public Type getSpecializedConstructorType(Type returnType) {
    return new Type(CVC4JNI.DatatypeConstructor_getSpecializedConstructorType(swigCPtr, this, Type.getCPtr(returnType), returnType), true);
  }

  public Cardinality getCardinality(Type t) {
    return new Cardinality(CVC4JNI.DatatypeConstructor_getCardinality(swigCPtr, this, Type.getCPtr(t), t), true);
  }

  public boolean isFinite(Type t) {
    return CVC4JNI.DatatypeConstructor_isFinite(swigCPtr, this, Type.getCPtr(t), t);
  }

  public boolean isInterpretedFinite(Type t) {
    return CVC4JNI.DatatypeConstructor_isInterpretedFinite(swigCPtr, this, Type.getCPtr(t), t);
  }

  public boolean isResolved() {
    return CVC4JNI.DatatypeConstructor_isResolved(swigCPtr, this);
  }

  public DatatypeConstructorArg get(long index) {
    return new DatatypeConstructorArg(CVC4JNI.DatatypeConstructor_get__SWIG_0(swigCPtr, this, index), false);
  }

  public DatatypeConstructorArg get(String name) {
    return new DatatypeConstructorArg(CVC4JNI.DatatypeConstructor_get__SWIG_1(swigCPtr, this, name), false);
  }

  public Expr getSelector(String name) {
    return new Expr(CVC4JNI.DatatypeConstructor_getSelector(swigCPtr, this, name), true);
  }

  public Type getArgType(long i) {
    return new Type(CVC4JNI.DatatypeConstructor_getArgType(swigCPtr, this, i), true);
  }

  public Expr getSelectorInternal(Type dtt, long index) {
    return new Expr(CVC4JNI.DatatypeConstructor_getSelectorInternal(swigCPtr, this, Type.getCPtr(dtt), dtt, index), true);
  }

  public int getSelectorIndexInternal(Expr sel) {
    return CVC4JNI.DatatypeConstructor_getSelectorIndexInternal(swigCPtr, this, Expr.getCPtr(sel), sel);
  }

  public boolean involvesExternalType() {
    return CVC4JNI.DatatypeConstructor_involvesExternalType(swigCPtr, this);
  }

  public boolean involvesUninterpretedType() {
    return CVC4JNI.DatatypeConstructor_involvesUninterpretedType(swigCPtr, this);
  }

  public void setSygus(Expr op, SWIGTYPE_p_std__shared_ptrT_CVC4__SygusPrintCallback_t spc) {
    CVC4JNI.DatatypeConstructor_setSygus(swigCPtr, this, Expr.getCPtr(op), op, SWIGTYPE_p_std__shared_ptrT_CVC4__SygusPrintCallback_t.getCPtr(spc));
  }

  public JavaIteratorAdapter_DatatypeConstructor iterator() {
    return new JavaIteratorAdapter_DatatypeConstructor(CVC4JNI.DatatypeConstructor_iterator(swigCPtr, this), true);
  }

  public String toString() {
    return CVC4JNI.DatatypeConstructor_toString(swigCPtr, this);
  }

}
