/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class DatatypeHashFunction {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DatatypeHashFunction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DatatypeHashFunction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_DatatypeHashFunction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long apply(Datatype dt) {
    return CVC4JNI.DatatypeHashFunction_apply__SWIG_0(swigCPtr, this, Datatype.getCPtr(dt), dt);
  }

  public long apply(DatatypeConstructor dtc) {
    return CVC4JNI.DatatypeHashFunction_apply__SWIG_1(swigCPtr, this, DatatypeConstructor.getCPtr(dtc), dtc);
  }

  public DatatypeHashFunction() {
    this(CVC4JNI.new_DatatypeHashFunction(), true);
  }

}
