/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class DeclarationDefinitionCommand extends Command {
  private transient long swigCPtr;

  protected DeclarationDefinitionCommand(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.DeclarationDefinitionCommand_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DeclarationDefinitionCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_DeclarationDefinitionCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void invoke(SmtEngine smtEngine) {
    CVC4JNI.DeclarationDefinitionCommand_invoke(swigCPtr, this, SmtEngine.getCPtr(smtEngine), smtEngine);
  }

  public String getSymbol() {
    return CVC4JNI.DeclarationDefinitionCommand_getSymbol(swigCPtr, this);
  }

}
