/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class DeclareSygusVarCommand extends DeclarationDefinitionCommand {
  private transient long swigCPtr;

  protected DeclareSygusVarCommand(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.DeclareSygusVarCommand_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DeclareSygusVarCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_DeclareSygusVarCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DeclareSygusVarCommand(String id, Expr var, Type type) {
    this(CVC4JNI.new_DeclareSygusVarCommand(id, Expr.getCPtr(var), var, Type.getCPtr(type), type), true);
  }

  public Expr getVar() {
    return new Expr(CVC4JNI.DeclareSygusVarCommand_getVar(swigCPtr, this), true);
  }

  public Type getType() {
    return new Type(CVC4JNI.DeclareSygusVarCommand_getType(swigCPtr, this), true);
  }

  public void invoke(SmtEngine smtEngine) {
    CVC4JNI.DeclareSygusVarCommand_invoke(swigCPtr, this, SmtEngine.getCPtr(smtEngine), smtEngine);
  }

  public Command exportTo(ExprManager exprManager, ExprManagerMapCollection variableMap) {
    long cPtr = CVC4JNI.DeclareSygusVarCommand_exportTo(swigCPtr, this, ExprManager.getCPtr(exprManager), exprManager, ExprManagerMapCollection.getCPtr(variableMap), variableMap);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

  public Command clone() {
    long cPtr = CVC4JNI.DeclareSygusVarCommand_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

  public String getCommandName() {
    return CVC4JNI.DeclareSygusVarCommand_getCommandName(swigCPtr, this);
  }

}
