/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class DeclareFunctionCommand extends DeclarationDefinitionCommand {
  private transient long swigCPtr;

  protected DeclareFunctionCommand(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.DeclareFunctionCommand_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DeclareFunctionCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_DeclareFunctionCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DeclareFunctionCommand(String id, Expr func, Type type) {
    this(CVC4JNI.new_DeclareFunctionCommand(id, Expr.getCPtr(func), func, Type.getCPtr(type), type), true);
  }

  public Expr getFunction() {
    return new Expr(CVC4JNI.DeclareFunctionCommand_getFunction(swigCPtr, this), true);
  }

  public Type getType() {
    return new Type(CVC4JNI.DeclareFunctionCommand_getType(swigCPtr, this), true);
  }

  public boolean getPrintInModel() {
    return CVC4JNI.DeclareFunctionCommand_getPrintInModel(swigCPtr, this);
  }

  public boolean getPrintInModelSetByUser() {
    return CVC4JNI.DeclareFunctionCommand_getPrintInModelSetByUser(swigCPtr, this);
  }

  public void setPrintInModel(boolean p) {
    CVC4JNI.DeclareFunctionCommand_setPrintInModel(swigCPtr, this, p);
  }

  public void invoke(SmtEngine smtEngine) {
    CVC4JNI.DeclareFunctionCommand_invoke(swigCPtr, this, SmtEngine.getCPtr(smtEngine), smtEngine);
  }

  public Command exportTo(ExprManager exprManager, ExprManagerMapCollection variableMap) {
    long cPtr = CVC4JNI.DeclareFunctionCommand_exportTo(swigCPtr, this, ExprManager.getCPtr(exprManager), exprManager, ExprManagerMapCollection.getCPtr(variableMap), variableMap);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

  public Command clone() {
    long cPtr = CVC4JNI.DeclareFunctionCommand_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

  public String getCommandName() {
    return CVC4JNI.DeclareFunctionCommand_getCommandName(swigCPtr, this);
  }

}
