/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class DefineNamedFunctionCommand extends DefineFunctionCommand {
  private transient long swigCPtr;

  protected DefineNamedFunctionCommand(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.DefineNamedFunctionCommand_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DefineNamedFunctionCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_DefineNamedFunctionCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DefineNamedFunctionCommand(String id, Expr func, vectorExpr formals, Expr formula) {
    this(CVC4JNI.new_DefineNamedFunctionCommand(id, Expr.getCPtr(func), func, vectorExpr.getCPtr(formals), formals, Expr.getCPtr(formula), formula), true);
  }

  public void invoke(SmtEngine smtEngine) {
    CVC4JNI.DefineNamedFunctionCommand_invoke(swigCPtr, this, SmtEngine.getCPtr(smtEngine), smtEngine);
  }

  public Command exportTo(ExprManager exprManager, ExprManagerMapCollection variableMap) {
    long cPtr = CVC4JNI.DefineNamedFunctionCommand_exportTo(swigCPtr, this, ExprManager.getCPtr(exprManager), exprManager, ExprManagerMapCollection.getCPtr(variableMap), variableMap);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

  public Command clone() {
    long cPtr = CVC4JNI.DefineNamedFunctionCommand_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

}
