/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class DefineTypeCommand extends DeclarationDefinitionCommand {
  private transient long swigCPtr;

  protected DefineTypeCommand(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.DefineTypeCommand_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DefineTypeCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_DefineTypeCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DefineTypeCommand(String id, Type t) {
    this(CVC4JNI.new_DefineTypeCommand__SWIG_0(id, Type.getCPtr(t), t), true);
  }

  public DefineTypeCommand(String id, vectorType params, Type t) {
    this(CVC4JNI.new_DefineTypeCommand__SWIG_1(id, vectorType.getCPtr(params), params, Type.getCPtr(t), t), true);
  }

  public vectorType getParameters() {
    return new vectorType(CVC4JNI.DefineTypeCommand_getParameters(swigCPtr, this), false);
  }

  public Type getType() {
    return new Type(CVC4JNI.DefineTypeCommand_getType(swigCPtr, this), true);
  }

  public void invoke(SmtEngine smtEngine) {
    CVC4JNI.DefineTypeCommand_invoke(swigCPtr, this, SmtEngine.getCPtr(smtEngine), smtEngine);
  }

  public Command exportTo(ExprManager exprManager, ExprManagerMapCollection variableMap) {
    long cPtr = CVC4JNI.DefineTypeCommand_exportTo(swigCPtr, this, ExprManager.getCPtr(exprManager), exprManager, ExprManagerMapCollection.getCPtr(variableMap), variableMap);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

  public Command clone() {
    long cPtr = CVC4JNI.DefineTypeCommand_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

  public String getCommandName() {
    return CVC4JNI.DefineTypeCommand_getCommandName(swigCPtr, this);
  }

}
