/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class EmptySet {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmptySet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmptySet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_EmptySet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EmptySet(SetType setType) {
    this(CVC4JNI.new_EmptySet__SWIG_0(SetType.getCPtr(setType), setType), true);
  }

  public EmptySet(EmptySet other) {
    this(CVC4JNI.new_EmptySet__SWIG_1(EmptySet.getCPtr(other), other), true);
  }

  public SetType getType() {
    return new SetType(CVC4JNI.EmptySet_getType(swigCPtr, this), false);
  }

  public boolean equals(EmptySet es) {
    return CVC4JNI.EmptySet_equals(swigCPtr, this, EmptySet.getCPtr(es), es);
  }

  public boolean less(EmptySet es) {
    return CVC4JNI.EmptySet_less(swigCPtr, this, EmptySet.getCPtr(es), es);
  }

  public boolean lessEqual(EmptySet es) {
    return CVC4JNI.EmptySet_lessEqual(swigCPtr, this, EmptySet.getCPtr(es), es);
  }

  public boolean greater(EmptySet es) {
    return CVC4JNI.EmptySet_greater(swigCPtr, this, EmptySet.getCPtr(es), es);
  }

  public boolean greaterEqual(EmptySet es) {
    return CVC4JNI.EmptySet_greaterEqual(swigCPtr, this, EmptySet.getCPtr(es), es);
  }

}
