/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class Exception extends RuntimeException {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Exception(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Exception obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_Exception(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Exception() {
    this(CVC4JNI.new_Exception__SWIG_0(), true);
  }

  public Exception(String msg) {
    this(CVC4JNI.new_Exception__SWIG_1(msg), true);
  }

  public void setMessage(String msg) {
    CVC4JNI.Exception_setMessage(swigCPtr, this, msg);
  }

  public String getMessage() {
    return CVC4JNI.Exception_getMessage(swigCPtr, this);
  }

  public String what() {
    return CVC4JNI.Exception_what(swigCPtr, this);
  }

  public String toString() {
    return CVC4JNI.Exception_toString(swigCPtr, this);
  }

  public void toStream(java.io.OutputStream os) {
    edu.nyu.acsys.CVC4.JavaOutputStreamAdapter tempos = new edu.nyu.acsys.CVC4.JavaOutputStreamAdapter();
    try {
      CVC4JNI.Exception_toStream(swigCPtr, this, edu.nyu.acsys.CVC4.JavaOutputStreamAdapter.getCPtr(tempos));
    } finally {
    new java.io.PrintStream(os).print(tempos.toString());
    }
  }

}
