/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class Input {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Input(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Input obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_Input(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static Input newFileInput(InputLanguage lang, String filename, boolean useMmap) {
    long cPtr = CVC4JNI.Input_newFileInput__SWIG_0(lang.swigValue(), filename, useMmap);
    return (cPtr == 0) ? null : new Input(cPtr, false);
  }

  public static Input newFileInput(InputLanguage lang, String filename) {
    long cPtr = CVC4JNI.Input_newFileInput__SWIG_1(lang.swigValue(), filename);
    return (cPtr == 0) ? null : new Input(cPtr, false);
  }

  public static Input newStreamInput(InputLanguage lang, java.io.InputStream input, String name, boolean lineBuffered) {
    edu.nyu.acsys.CVC4.JavaInputStreamAdapter tempinput = edu.nyu.acsys.CVC4.JavaInputStreamAdapter.get(input);
    {
      long cPtr = CVC4JNI.Input_newStreamInput__SWIG_0(lang.swigValue(), edu.nyu.acsys.CVC4.JavaInputStreamAdapter.getCPtr(tempinput), name, lineBuffered);
      return (cPtr == 0) ? null : new Input(cPtr, false);
    }
  }

  public static Input newStreamInput(InputLanguage lang, java.io.InputStream input, String name) {
    edu.nyu.acsys.CVC4.JavaInputStreamAdapter tempinput = edu.nyu.acsys.CVC4.JavaInputStreamAdapter.get(input);
    {
      long cPtr = CVC4JNI.Input_newStreamInput__SWIG_1(lang.swigValue(), edu.nyu.acsys.CVC4.JavaInputStreamAdapter.getCPtr(tempinput), name);
      return (cPtr == 0) ? null : new Input(cPtr, false);
    }
  }

  public static Input newStringInput(InputLanguage lang, String input, String name) {
    long cPtr = CVC4JNI.Input_newStringInput(lang.swigValue(), input, name);
    return (cPtr == 0) ? null : new Input(cPtr, false);
  }

  public String getInputStreamName() {
    return CVC4JNI.Input_getInputStreamName(swigCPtr, this);
  }

}
