/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class IntToBitVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IntToBitVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntToBitVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_IntToBitVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSize(long value) {
    CVC4JNI.IntToBitVector_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return CVC4JNI.IntToBitVector_size_get(swigCPtr, this);
  }

  public IntToBitVector(long size) {
    this(CVC4JNI.new_IntToBitVector(size), true);
  }

  public long toUnsigned() {
    return CVC4JNI.IntToBitVector_toUnsigned(swigCPtr, this);
  }

}
