/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class JavaInputStreamAdapter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected JavaInputStreamAdapter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JavaInputStreamAdapter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    streams.remove(getInputStream());
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_JavaInputStreamAdapter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  private static java.util.HashMap<java.io.InputStream, JavaInputStreamAdapter> streams =
    new java.util.HashMap<java.io.InputStream, JavaInputStreamAdapter>();
  public static JavaInputStreamAdapter get(java.io.InputStream is) {
    if(streams.containsKey(is)) {
      return (JavaInputStreamAdapter) streams.get(is);
    }
    JavaInputStreamAdapter adapter = new JavaInputStreamAdapter(is);
    streams.put(is, adapter);
    return adapter;
  }

  private JavaInputStreamAdapter(Object inputStream) {
    this(CVC4JNI.new_JavaInputStreamAdapter(inputStream), true);
  }

  private Object getInputStream() {
    return CVC4JNI.JavaInputStreamAdapter_getInputStream(swigCPtr, this);
  }

}
