/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

class JavaIteratorAdapter_StatisticsBase implements java.util.Iterator<Object[]> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected JavaIteratorAdapter_StatisticsBase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JavaIteratorAdapter_StatisticsBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_JavaIteratorAdapter_StatisticsBase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void remove() {
    throw new java.lang.UnsupportedOperationException();
  }

  public Object[] next() {
    if(hasNext()) {
      return getNext();
    } else {
      throw new java.util.NoSuchElementException();
    }
  }

  public JavaIteratorAdapter_StatisticsBase(StatisticsBase t) {
    this(CVC4JNI.new_JavaIteratorAdapter_StatisticsBase(StatisticsBase.getCPtr(t), t), true);
  }

  public boolean hasNext() {
    return CVC4JNI.JavaIteratorAdapter_StatisticsBase_hasNext(swigCPtr, this);
  }

  private java.lang.Object[] getNext() { return CVC4JNI.JavaIteratorAdapter_StatisticsBase_getNext(swigCPtr, this); }

}
