/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class ParserExprStream extends ExprStream {
  private transient long swigCPtr;

  protected ParserExprStream(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.ParserExprStream_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParserExprStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_ParserExprStream(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ParserExprStream(Parser parser) {
    this(CVC4JNI.new_ParserExprStream(Parser.getCPtr(parser), parser), true);
  }

  public Expr nextExpr() {
    return new Expr(CVC4JNI.ParserExprStream_nextExpr(swigCPtr, this), true);
  }

}
