/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class PrettySExprs {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PrettySExprs(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PrettySExprs obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_PrettySExprs(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PrettySExprs(boolean prettySExprs) {
    this(CVC4JNI.new_PrettySExprs(prettySExprs), true);
  }

  public void applyPrettySExprs(java.io.OutputStream out) {
    JavaOutputStreamAdapter tempout = new JavaOutputStreamAdapter();
    try {
      CVC4JNI.PrettySExprs_applyPrettySExprs(swigCPtr, this, JavaOutputStreamAdapter.getCPtr(tempout));
    } finally {
    new java.io.PrintStream(out).print(tempout.toString());
    }
  }

  public static boolean getPrettySExprs(java.io.OutputStream out) {
    JavaOutputStreamAdapter tempout = new JavaOutputStreamAdapter();
    try {
      return CVC4JNI.PrettySExprs_getPrettySExprs(JavaOutputStreamAdapter.getCPtr(tempout));
    } finally {
    new java.io.PrintStream(out).print(tempout.toString());
    }
  }

  public static void setPrettySExprs(java.io.OutputStream out, boolean prettySExprs) {
    JavaOutputStreamAdapter tempout = new JavaOutputStreamAdapter();
    try {
      CVC4JNI.PrettySExprs_setPrettySExprs(JavaOutputStreamAdapter.getCPtr(tempout), prettySExprs);
    } finally {
    new java.io.PrintStream(out).print(tempout.toString());
    }
  }

  static public class Scope {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Scope(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Scope obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
/*     protected void finalize() {
      delete();
    } */
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CVC4JNI.delete_PrettySExprs_Scope(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    static private long SwigConstructScope(java.io.OutputStream out, boolean prettySExprs) {
      JavaOutputStreamAdapter tempout = new JavaOutputStreamAdapter();
      try {
        return CVC4JNI.new_PrettySExprs_Scope(JavaOutputStreamAdapter.getCPtr(tempout), prettySExprs);
      } finally {
      new java.io.PrintStream(out).print(tempout.toString());
      }
    }
  
    public Scope(java.io.OutputStream out, boolean prettySExprs) {
      this(Scope.SwigConstructScope(out, prettySExprs), true);
    }
  
  }

}
