/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class SetExpressionNameCommand extends Command {
  private transient long swigCPtr;

  protected SetExpressionNameCommand(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.SetExpressionNameCommand_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SetExpressionNameCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_SetExpressionNameCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SetExpressionNameCommand(Expr expr, String name) {
    this(CVC4JNI.new_SetExpressionNameCommand(Expr.getCPtr(expr), expr, name), true);
  }

  public void invoke(SmtEngine smtEngine) {
    CVC4JNI.SetExpressionNameCommand_invoke(swigCPtr, this, SmtEngine.getCPtr(smtEngine), smtEngine);
  }

  public Command exportTo(ExprManager exprManager, ExprManagerMapCollection variableMap) {
    long cPtr = CVC4JNI.SetExpressionNameCommand_exportTo(swigCPtr, this, ExprManager.getCPtr(exprManager), exprManager, ExprManagerMapCollection.getCPtr(variableMap), variableMap);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

  public Command clone() {
    long cPtr = CVC4JNI.SetExpressionNameCommand_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

  public String getCommandName() {
    return CVC4JNI.SetExpressionNameCommand_getCommandName(swigCPtr, this);
  }

}
