/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class SetType extends Type {
  private transient long swigCPtr;

  protected SetType(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.SetType_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SetType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_SetType(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SetType(Type type) {
    this(CVC4JNI.new_SetType__SWIG_0(Type.getCPtr(type), type), true);
  }

  public SetType() {
    this(CVC4JNI.new_SetType__SWIG_1(), true);
  }

  public Type getElementType() {
    return new Type(CVC4JNI.SetType_getElementType(swigCPtr, this), true);
  }

}
