/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class SExpr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SExpr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SExpr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_SExpr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SExpr() {
    this(CVC4JNI.new_SExpr__SWIG_0(), true);
  }

  public SExpr(SExpr arg0) {
    this(CVC4JNI.new_SExpr__SWIG_1(SExpr.getCPtr(arg0), arg0), true);
  }

  public SExpr(Integer value) {
    this(CVC4JNI.new_SExpr__SWIG_2(Integer.getCPtr(value), value), true);
  }

  public SExpr(int value) {
    this(CVC4JNI.new_SExpr__SWIG_3(value), true);
  }

  public SExpr(Rational value) {
    this(CVC4JNI.new_SExpr__SWIG_4(Rational.getCPtr(value), value), true);
  }

  public SExpr(String value) {
    this(CVC4JNI.new_SExpr__SWIG_5(value), true);
  }

  public SExpr(boolean value) {
    this(CVC4JNI.new_SExpr__SWIG_6(value), true);
  }

  public SExpr(SExprKeyword value) {
    this(CVC4JNI.new_SExpr__SWIG_7(SExprKeyword.getCPtr(value), value), true);
  }

  public SExpr(vectorSExpr children) {
    this(CVC4JNI.new_SExpr__SWIG_8(vectorSExpr.getCPtr(children), children), true);
  }

  public boolean isAtom() {
    return CVC4JNI.SExpr_isAtom(swigCPtr, this);
  }

  public boolean isInteger() {
    return CVC4JNI.SExpr_isInteger(swigCPtr, this);
  }

  public boolean isRational() {
    return CVC4JNI.SExpr_isRational(swigCPtr, this);
  }

  public boolean isString() {
    return CVC4JNI.SExpr_isString(swigCPtr, this);
  }

  public boolean isKeyword() {
    return CVC4JNI.SExpr_isKeyword(swigCPtr, this);
  }

  public String getValue() {
    return CVC4JNI.SExpr_getValue(swigCPtr, this);
  }

  public Integer getIntegerValue() {
    return new Integer(CVC4JNI.SExpr_getIntegerValue(swigCPtr, this), false);
  }

  public Rational getRationalValue() {
    return new Rational(CVC4JNI.SExpr_getRationalValue(swigCPtr, this), false);
  }

  public vectorSExpr getChildren() {
    return new vectorSExpr(CVC4JNI.SExpr_getChildren(swigCPtr, this), false);
  }

  public boolean equals(SExpr s) {
    return CVC4JNI.SExpr_equals(swigCPtr, this, SExpr.getCPtr(s), s);
  }

  public static SExpr parseAtom(String atom) {
    return new SExpr(CVC4JNI.SExpr_parseAtom(atom), true);
  }

  public static SExpr parseListOfAtoms(vectorString atoms) {
    return new SExpr(CVC4JNI.SExpr_parseListOfAtoms(vectorString.getCPtr(atoms), atoms), true);
  }

  public static SExpr parseListOfListOfAtoms(SWIGTYPE_p_std__vectorT_std__vectorT_std__string_t_t atoms_lists) {
    return new SExpr(CVC4JNI.SExpr_parseListOfListOfAtoms(SWIGTYPE_p_std__vectorT_std__vectorT_std__string_t_t.getCPtr(atoms_lists)), true);
  }

  public static void toStream(java.io.OutputStream out, SExpr sexpr) {
    edu.nyu.acsys.CVC4.JavaOutputStreamAdapter tempout = new edu.nyu.acsys.CVC4.JavaOutputStreamAdapter();
    try {
      CVC4JNI.SExpr_toStream__SWIG_0(edu.nyu.acsys.CVC4.JavaOutputStreamAdapter.getCPtr(tempout), SExpr.getCPtr(sexpr), sexpr);
    } finally {
    new java.io.PrintStream(out).print(tempout.toString());
    }
  }

  public static void toStream(java.io.OutputStream out, SExpr sexpr, OutputLanguage language) {
    edu.nyu.acsys.CVC4.JavaOutputStreamAdapter tempout = new edu.nyu.acsys.CVC4.JavaOutputStreamAdapter();
    try {
      CVC4JNI.SExpr_toStream__SWIG_1(edu.nyu.acsys.CVC4.JavaOutputStreamAdapter.getCPtr(tempout), SExpr.getCPtr(sexpr), sexpr, language.swigValue());
    } finally {
    new java.io.PrintStream(out).print(tempout.toString());
    }
  }

  public static void toStream(java.io.OutputStream out, SExpr sexpr, OutputLanguage language, int indent) {
    edu.nyu.acsys.CVC4.JavaOutputStreamAdapter tempout = new edu.nyu.acsys.CVC4.JavaOutputStreamAdapter();
    try {
      CVC4JNI.SExpr_toStream__SWIG_2(edu.nyu.acsys.CVC4.JavaOutputStreamAdapter.getCPtr(tempout), SExpr.getCPtr(sexpr), sexpr, language.swigValue(), indent);
    } finally {
    new java.io.PrintStream(out).print(tempout.toString());
    }
  }

  public String toString() {
    return CVC4JNI.SExpr_toString(swigCPtr, this);
  }

}
