/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class SExprType extends Type {
  private transient long swigCPtr;

  protected SExprType(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.SExprType_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SExprType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_SExprType(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SExprType(Type type) {
    this(CVC4JNI.new_SExprType__SWIG_0(Type.getCPtr(type), type), true);
  }

  public SExprType() {
    this(CVC4JNI.new_SExprType__SWIG_1(), true);
  }

  public vectorType getTypes() {
    return new vectorType(CVC4JNI.SExprType_getTypes(swigCPtr, this), true);
  }

}
