/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class SortType extends Type {
  private transient long swigCPtr;

  protected SortType(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.SortType_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SortType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_SortType(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SortType(Type type) {
    this(CVC4JNI.new_SortType__SWIG_0(Type.getCPtr(type), type), true);
  }

  public SortType() {
    this(CVC4JNI.new_SortType__SWIG_1(), true);
  }

  public String getName() {
    return CVC4JNI.SortType_getName(swigCPtr, this);
  }

  public boolean isParameterized() {
    return CVC4JNI.SortType_isParameterized(swigCPtr, this);
  }

  public vectorType getParamTypes() {
    return new vectorType(CVC4JNI.SortType_getParamTypes(swigCPtr, this), true);
  }

}
