/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class StringType extends Type {
  private transient long swigCPtr;

  protected StringType(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.StringType_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_StringType(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public StringType(Type type) {
    this(CVC4JNI.new_StringType(Type.getCPtr(type), type), true);
  }

}
