/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class SygusGTerm {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SygusGTerm(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SygusGTerm obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_SygusGTerm(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setD_type(Type value) {
    CVC4JNI.SygusGTerm_d_type_set(swigCPtr, this, Type.getCPtr(value), value);
  }

  public Type getD_type() {
    long cPtr = CVC4JNI.SygusGTerm_d_type_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Type(cPtr, false);
  }

  public void setD_expr(Expr value) {
    CVC4JNI.SygusGTerm_d_expr_set(swigCPtr, this, Expr.getCPtr(value), value);
  }

  public Expr getD_expr() {
    long cPtr = CVC4JNI.SygusGTerm_d_expr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Expr(cPtr, false);
  }

  public void setD_let_vars(vectorExpr value) {
    CVC4JNI.SygusGTerm_d_let_vars_set(swigCPtr, this, vectorExpr.getCPtr(value), value);
  }

  public vectorExpr getD_let_vars() {
    long cPtr = CVC4JNI.SygusGTerm_d_let_vars_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vectorExpr(cPtr, false);
  }

  public void setD_gterm_type(long value) {
    CVC4JNI.SygusGTerm_d_gterm_type_set(swigCPtr, this, value);
  }

  public long getD_gterm_type() {
    return CVC4JNI.SygusGTerm_d_gterm_type_get(swigCPtr, this);
  }

  public void setD_name(String value) {
    CVC4JNI.SygusGTerm_d_name_set(swigCPtr, this, value);
  }

  public String getD_name() {
    return CVC4JNI.SygusGTerm_d_name_get(swigCPtr, this);
  }

  public void setD_children(SWIGTYPE_p_std__vectorT_CVC4__SygusGTerm_t value) {
    CVC4JNI.SygusGTerm_d_children_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_CVC4__SygusGTerm_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_CVC4__SygusGTerm_t getD_children() {
    long cPtr = CVC4JNI.SygusGTerm_d_children_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_CVC4__SygusGTerm_t(cPtr, false);
  }

  public long getNumChildren() {
    return CVC4JNI.SygusGTerm_getNumChildren(swigCPtr, this);
  }

  public void addChild() {
    CVC4JNI.SygusGTerm_addChild(swigCPtr, this);
  }

  public SygusGTerm() {
    this(CVC4JNI.new_SygusGTerm(), true);
  }

  public final static int gterm_op = CVC4JNI.SygusGTerm_gterm_op_get();
  public final static int gterm_let = CVC4JNI.SygusGTerm_gterm_let_get();
  public final static int gterm_constant = CVC4JNI.SygusGTerm_gterm_constant_get();
  public final static int gterm_variable = CVC4JNI.SygusGTerm_gterm_variable_get();
  public final static int gterm_input_variable = CVC4JNI.SygusGTerm_gterm_input_variable_get();
  public final static int gterm_local_variable = CVC4JNI.SygusGTerm_gterm_local_variable_get();
  public final static int gterm_nested_sort = CVC4JNI.SygusGTerm_gterm_nested_sort_get();
  public final static int gterm_unresolved = CVC4JNI.SygusGTerm_gterm_unresolved_get();
  public final static int gterm_ignore = CVC4JNI.SygusGTerm_gterm_ignore_get();

}
