/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class SymbolTable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SymbolTable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SymbolTable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_SymbolTable(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SymbolTable() {
    this(CVC4JNI.new_SymbolTable(), true);
  }

  public boolean bind(String name, Expr obj, boolean levelZero, boolean doOverload) {
    return CVC4JNI.SymbolTable_bind__SWIG_0(swigCPtr, this, name, Expr.getCPtr(obj), obj, levelZero, doOverload);
  }

  public boolean bind(String name, Expr obj, boolean levelZero) {
    return CVC4JNI.SymbolTable_bind__SWIG_1(swigCPtr, this, name, Expr.getCPtr(obj), obj, levelZero);
  }

  public boolean bind(String name, Expr obj) {
    return CVC4JNI.SymbolTable_bind__SWIG_2(swigCPtr, this, name, Expr.getCPtr(obj), obj);
  }

  public boolean bindDefinedFunction(String name, Expr obj, boolean levelZero, boolean doOverload) {
    return CVC4JNI.SymbolTable_bindDefinedFunction__SWIG_0(swigCPtr, this, name, Expr.getCPtr(obj), obj, levelZero, doOverload);
  }

  public boolean bindDefinedFunction(String name, Expr obj, boolean levelZero) {
    return CVC4JNI.SymbolTable_bindDefinedFunction__SWIG_1(swigCPtr, this, name, Expr.getCPtr(obj), obj, levelZero);
  }

  public boolean bindDefinedFunction(String name, Expr obj) {
    return CVC4JNI.SymbolTable_bindDefinedFunction__SWIG_2(swigCPtr, this, name, Expr.getCPtr(obj), obj);
  }

  public void bindType(String name, Type t, boolean levelZero) {
    CVC4JNI.SymbolTable_bindType__SWIG_0(swigCPtr, this, name, Type.getCPtr(t), t, levelZero);
  }

  public void bindType(String name, Type t) {
    CVC4JNI.SymbolTable_bindType__SWIG_1(swigCPtr, this, name, Type.getCPtr(t), t);
  }

  public void bindType(String name, vectorType params, Type t, boolean levelZero) {
    CVC4JNI.SymbolTable_bindType__SWIG_2(swigCPtr, this, name, vectorType.getCPtr(params), params, Type.getCPtr(t), t, levelZero);
  }

  public void bindType(String name, vectorType params, Type t) {
    CVC4JNI.SymbolTable_bindType__SWIG_3(swigCPtr, this, name, vectorType.getCPtr(params), params, Type.getCPtr(t), t);
  }

  public boolean isBound(String name) {
    return CVC4JNI.SymbolTable_isBound(swigCPtr, this, name);
  }

  public boolean isBoundDefinedFunction(String name) {
    return CVC4JNI.SymbolTable_isBoundDefinedFunction__SWIG_0(swigCPtr, this, name);
  }

  public boolean isBoundDefinedFunction(Expr func) {
    return CVC4JNI.SymbolTable_isBoundDefinedFunction__SWIG_1(swigCPtr, this, Expr.getCPtr(func), func);
  }

  public boolean isBoundType(String name) {
    return CVC4JNI.SymbolTable_isBoundType(swigCPtr, this, name);
  }

  public Expr lookup(String name) {
    return new Expr(CVC4JNI.SymbolTable_lookup(swigCPtr, this, name), true);
  }

  public Type lookupType(String name) {
    return new Type(CVC4JNI.SymbolTable_lookupType__SWIG_0(swigCPtr, this, name), true);
  }

  public Type lookupType(String name, vectorType params) {
    return new Type(CVC4JNI.SymbolTable_lookupType__SWIG_1(swigCPtr, this, name, vectorType.getCPtr(params), params), true);
  }

  public long lookupArity(String name) {
    return CVC4JNI.SymbolTable_lookupArity(swigCPtr, this, name);
  }

  public void popScope() {
    CVC4JNI.SymbolTable_popScope(swigCPtr, this);
  }

  public void pushScope() {
    CVC4JNI.SymbolTable_pushScope(swigCPtr, this);
  }

  public long getLevel() {
    return CVC4JNI.SymbolTable_getLevel(swigCPtr, this);
  }

  public void reset() {
    CVC4JNI.SymbolTable_reset(swigCPtr, this);
  }

  public boolean isOverloadedFunction(Expr fun) {
    return CVC4JNI.SymbolTable_isOverloadedFunction(swigCPtr, this, Expr.getCPtr(fun), fun);
  }

  public Expr getOverloadedConstantForType(String name, Type t) {
    return new Expr(CVC4JNI.SymbolTable_getOverloadedConstantForType(swigCPtr, this, name, Type.getCPtr(t), t), true);
  }

  public Expr getOverloadedFunctionForTypes(String name, vectorType argTypes) {
    return new Expr(CVC4JNI.SymbolTable_getOverloadedFunctionForTypes(swigCPtr, this, name, vectorType.getCPtr(argTypes), argTypes), true);
  }

}
