/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public final class TheoryId {
  public final static TheoryId THEORY_BUILTIN = new TheoryId("THEORY_BUILTIN");
  public final static TheoryId THEORY_BOOL = new TheoryId("THEORY_BOOL");
  public final static TheoryId THEORY_UF = new TheoryId("THEORY_UF");
  public final static TheoryId THEORY_ARITH = new TheoryId("THEORY_ARITH");
  public final static TheoryId THEORY_BV = new TheoryId("THEORY_BV");
  public final static TheoryId THEORY_FP = new TheoryId("THEORY_FP");
  public final static TheoryId THEORY_ARRAYS = new TheoryId("THEORY_ARRAYS");
  public final static TheoryId THEORY_DATATYPES = new TheoryId("THEORY_DATATYPES");
  public final static TheoryId THEORY_SEP = new TheoryId("THEORY_SEP");
  public final static TheoryId THEORY_SETS = new TheoryId("THEORY_SETS");
  public final static TheoryId THEORY_STRINGS = new TheoryId("THEORY_STRINGS");
  public final static TheoryId THEORY_QUANTIFIERS = new TheoryId("THEORY_QUANTIFIERS");
  public final static TheoryId THEORY_LAST = new TheoryId("THEORY_LAST");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TheoryId swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TheoryId.class + " with value " + swigValue);
  }

  private TheoryId(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TheoryId(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TheoryId(String swigName, TheoryId swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TheoryId[] swigValues = { THEORY_BUILTIN, THEORY_BOOL, THEORY_UF, THEORY_ARITH, THEORY_BV, THEORY_FP, THEORY_ARRAYS, THEORY_DATATYPES, THEORY_SEP, THEORY_SETS, THEORY_STRINGS, THEORY_QUANTIFIERS, THEORY_LAST };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

