/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class TupleUpdate {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TupleUpdate(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TupleUpdate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_TupleUpdate(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TupleUpdate(long index) {
    this(CVC4JNI.new_TupleUpdate(index), true);
  }

  public long getIndex() {
    return CVC4JNI.TupleUpdate_getIndex(swigCPtr, this);
  }

  public boolean equals(TupleUpdate t) {
    return CVC4JNI.TupleUpdate_equals(swigCPtr, this, TupleUpdate.getCPtr(t), t);
  }

}
