/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public final class TypeConstant {
  public final static TypeConstant BUILTIN_OPERATOR_TYPE = new TypeConstant("BUILTIN_OPERATOR_TYPE");
  public final static TypeConstant BOOLEAN_TYPE = new TypeConstant("BOOLEAN_TYPE");
  public final static TypeConstant REAL_TYPE = new TypeConstant("REAL_TYPE");
  public final static TypeConstant INTEGER_TYPE = new TypeConstant("INTEGER_TYPE");
  public final static TypeConstant ROUNDINGMODE_TYPE = new TypeConstant("ROUNDINGMODE_TYPE");
  public final static TypeConstant STRING_TYPE = new TypeConstant("STRING_TYPE");
  public final static TypeConstant REGEXP_TYPE = new TypeConstant("REGEXP_TYPE");
  public final static TypeConstant BOUND_VAR_LIST_TYPE = new TypeConstant("BOUND_VAR_LIST_TYPE");
  public final static TypeConstant INST_PATTERN_TYPE = new TypeConstant("INST_PATTERN_TYPE");
  public final static TypeConstant INST_PATTERN_LIST_TYPE = new TypeConstant("INST_PATTERN_LIST_TYPE");
  public final static TypeConstant RRHB_TYPE = new TypeConstant("RRHB_TYPE");
  public final static TypeConstant LAST_TYPE = new TypeConstant("LAST_TYPE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TypeConstant swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TypeConstant.class + " with value " + swigValue);
  }

  private TypeConstant(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TypeConstant(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TypeConstant(String swigName, TypeConstant swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TypeConstant[] swigValues = { BUILTIN_OPERATOR_TYPE, BOOLEAN_TYPE, REAL_TYPE, INTEGER_TYPE, ROUNDINGMODE_TYPE, STRING_TYPE, REGEXP_TYPE, BOUND_VAR_LIST_TYPE, INST_PATTERN_TYPE, INST_PATTERN_LIST_TYPE, RRHB_TYPE, LAST_TYPE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

