/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class TypeCheckingException extends Exception {
  private transient long swigCPtr;

  protected TypeCheckingException(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.TypeCheckingException_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TypeCheckingException obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_TypeCheckingException(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TypeCheckingException(Expr expr, String message) {
    this(CVC4JNI.new_TypeCheckingException__SWIG_2(Expr.getCPtr(expr), expr, message), true);
  }

  public TypeCheckingException(TypeCheckingException t) {
    this(CVC4JNI.new_TypeCheckingException__SWIG_3(TypeCheckingException.getCPtr(t), t), true);
  }

  public Expr getExpression() {
    return new Expr(CVC4JNI.TypeCheckingException_getExpression(swigCPtr, this), true);
  }

  public void toStream(java.io.OutputStream out) {
    edu.nyu.acsys.CVC4.JavaOutputStreamAdapter tempout = new edu.nyu.acsys.CVC4.JavaOutputStreamAdapter();
    try {
      CVC4JNI.TypeCheckingException_toStream(swigCPtr, this, edu.nyu.acsys.CVC4.JavaOutputStreamAdapter.getCPtr(tempout));
    } finally {
    new java.io.PrintStream(out).print(tempout.toString());
    }
  }

}
