/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class VariableTypeMap {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VariableTypeMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VariableTypeMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_VariableTypeMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Expr get(Expr e) {
    return new Expr(CVC4JNI.VariableTypeMap_get__SWIG_0(swigCPtr, this, Expr.getCPtr(e), e), false);
  }

  public Type get(Type t) {
    return new Type(CVC4JNI.VariableTypeMap_get__SWIG_1(swigCPtr, this, Type.getCPtr(t), t), false);
  }

  public VariableTypeMap() {
    this(CVC4JNI.new_VariableTypeMap(), true);
  }

}
