/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class vectorPairStringType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected vectorPairStringType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorPairStringType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_vectorPairStringType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorPairStringType() {
    this(CVC4JNI.new_vectorPairStringType__SWIG_0(), true);
  }

  public vectorPairStringType(long n) {
    this(CVC4JNI.new_vectorPairStringType__SWIG_1(n), true);
  }

  public long size() {
    return CVC4JNI.vectorPairStringType_size(swigCPtr, this);
  }

  public long capacity() {
    return CVC4JNI.vectorPairStringType_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    CVC4JNI.vectorPairStringType_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return CVC4JNI.vectorPairStringType_isEmpty(swigCPtr, this);
  }

  public void clear() {
    CVC4JNI.vectorPairStringType_clear(swigCPtr, this);
  }

  public void add(pairStringType x) {
    CVC4JNI.vectorPairStringType_add(swigCPtr, this, pairStringType.getCPtr(x), x);
  }

  public pairStringType get(int i) {
    return new pairStringType(CVC4JNI.vectorPairStringType_get(swigCPtr, this, i), false);
  }

  public void set(int i, pairStringType val) {
    CVC4JNI.vectorPairStringType_set(swigCPtr, this, i, pairStringType.getCPtr(val), val);
  }

}
