/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class vectorDatatypeType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected vectorDatatypeType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorDatatypeType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_vectorDatatypeType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorDatatypeType() {
    this(CVC4JNI.new_vectorDatatypeType__SWIG_0(), true);
  }

  public vectorDatatypeType(long n) {
    this(CVC4JNI.new_vectorDatatypeType__SWIG_1(n), true);
  }

  public long size() {
    return CVC4JNI.vectorDatatypeType_size(swigCPtr, this);
  }

  public long capacity() {
    return CVC4JNI.vectorDatatypeType_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    CVC4JNI.vectorDatatypeType_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return CVC4JNI.vectorDatatypeType_isEmpty(swigCPtr, this);
  }

  public void clear() {
    CVC4JNI.vectorDatatypeType_clear(swigCPtr, this);
  }

  public void add(DatatypeType x) {
    CVC4JNI.vectorDatatypeType_add(swigCPtr, this, DatatypeType.getCPtr(x), x);
  }

  public DatatypeType get(int i) {
    return new DatatypeType(CVC4JNI.vectorDatatypeType_get(swigCPtr, this, i), false);
  }

  public void set(int i, DatatypeType val) {
    CVC4JNI.vectorDatatypeType_set(swigCPtr, this, i, DatatypeType.getCPtr(val), val);
  }

}
