/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class vectorString {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected vectorString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_vectorString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorString() {
    this(CVC4JNI.new_vectorString__SWIG_0(), true);
  }

  public vectorString(long n) {
    this(CVC4JNI.new_vectorString__SWIG_1(n), true);
  }

  public long size() {
    return CVC4JNI.vectorString_size(swigCPtr, this);
  }

  public long capacity() {
    return CVC4JNI.vectorString_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    CVC4JNI.vectorString_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return CVC4JNI.vectorString_isEmpty(swigCPtr, this);
  }

  public void clear() {
    CVC4JNI.vectorString_clear(swigCPtr, this);
  }

  public void add(String x) {
    CVC4JNI.vectorString_add(swigCPtr, this, x);
  }

  public String get(int i) {
    return CVC4JNI.vectorString_get(swigCPtr, this, i);
  }

  public void set(int i, String val) {
    CVC4JNI.vectorString_set(swigCPtr, this, i, val);
  }

}
