/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class vectorDatatype {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected vectorDatatype(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorDatatype obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_vectorDatatype(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorDatatype() {
    this(CVC4JNI.new_vectorDatatype(), true);
  }

  public long size() {
    return CVC4JNI.vectorDatatype_size(swigCPtr, this);
  }

  public long capacity() {
    return CVC4JNI.vectorDatatype_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    CVC4JNI.vectorDatatype_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return CVC4JNI.vectorDatatype_isEmpty(swigCPtr, this);
  }

  public void clear() {
    CVC4JNI.vectorDatatype_clear(swigCPtr, this);
  }

  public void add(Datatype x) {
    CVC4JNI.vectorDatatype_add(swigCPtr, this, Datatype.getCPtr(x), x);
  }

  public Datatype get(int i) {
    return new Datatype(CVC4JNI.vectorDatatype_get(swigCPtr, this, i), false);
  }

  public void set(int i, Datatype val) {
    CVC4JNI.vectorDatatype_set(swigCPtr, this, i, Datatype.getCPtr(val), val);
  }

}
