/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class vectorType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected vectorType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

/*   protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_vectorType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorType() {
    this(CVC4JNI.new_vectorType__SWIG_0(), true);
  }

  public vectorType(long n) {
    this(CVC4JNI.new_vectorType__SWIG_1(n), true);
  }

  public long size() {
    return CVC4JNI.vectorType_size(swigCPtr, this);
  }

  public long capacity() {
    return CVC4JNI.vectorType_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    CVC4JNI.vectorType_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return CVC4JNI.vectorType_isEmpty(swigCPtr, this);
  }

  public void clear() {
    CVC4JNI.vectorType_clear(swigCPtr, this);
  }

  public void add(Type x) {
    CVC4JNI.vectorType_add(swigCPtr, this, Type.getCPtr(x), x);
  }

  public Type get(int i) {
    return new Type(CVC4JNI.vectorType_get(swigCPtr, this, i), false);
  }

  public void set(int i, Type val) {
    CVC4JNI.vectorType_set(swigCPtr, this, i, Type.getCPtr(val), val);
  }

}
