/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class BitVectorRepeat {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BitVectorRepeat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BitVectorRepeat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_BitVectorRepeat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRepeatAmount(long value) {
    CVC4JNI.BitVectorRepeat_repeatAmount_set(swigCPtr, this, value);
  }

  public long getRepeatAmount() {
    return CVC4JNI.BitVectorRepeat_repeatAmount_get(swigCPtr, this);
  }

  public BitVectorRepeat(long repeatAmount) {
    this(CVC4JNI.new_BitVectorRepeat(repeatAmount), true);
  }

  public long toUnsigned() {
    return CVC4JNI.BitVectorRepeat_toUnsigned(swigCPtr, this);
  }

}
