/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class CVC4 {
  public static boolean isInputLang_smt2(InputLanguage lang) {
    return CVC4JNI.isInputLang_smt2(lang.swigValue());
  }

  public static boolean isOutputLang_smt2(OutputLanguage lang) {
    return CVC4JNI.isOutputLang_smt2(lang.swigValue());
  }

  public static boolean isInputLang_smt2_5(InputLanguage lang, boolean exact) {
    return CVC4JNI.isInputLang_smt2_5__SWIG_0(lang.swigValue(), exact);
  }

  public static boolean isInputLang_smt2_5(InputLanguage lang) {
    return CVC4JNI.isInputLang_smt2_5__SWIG_1(lang.swigValue());
  }

  public static boolean isOutputLang_smt2_5(OutputLanguage lang, boolean exact) {
    return CVC4JNI.isOutputLang_smt2_5__SWIG_0(lang.swigValue(), exact);
  }

  public static boolean isOutputLang_smt2_5(OutputLanguage lang) {
    return CVC4JNI.isOutputLang_smt2_5__SWIG_1(lang.swigValue());
  }

  public static boolean isInputLang_smt2_6(InputLanguage lang, boolean exact) {
    return CVC4JNI.isInputLang_smt2_6__SWIG_0(lang.swigValue(), exact);
  }

  public static boolean isInputLang_smt2_6(InputLanguage lang) {
    return CVC4JNI.isInputLang_smt2_6__SWIG_1(lang.swigValue());
  }

  public static boolean isOutputLang_smt2_6(OutputLanguage lang, boolean exact) {
    return CVC4JNI.isOutputLang_smt2_6__SWIG_0(lang.swigValue(), exact);
  }

  public static boolean isOutputLang_smt2_6(OutputLanguage lang) {
    return CVC4JNI.isOutputLang_smt2_6__SWIG_1(lang.swigValue());
  }

  public static InputLanguage toInputLanguage(OutputLanguage language) {
    return InputLanguage.swigToEnum(CVC4JNI.toInputLanguage__SWIG_0(language.swigValue()));
  }

  public static OutputLanguage toOutputLanguage(InputLanguage language) {
    return OutputLanguage.swigToEnum(CVC4JNI.toOutputLanguage__SWIG_0(language.swigValue()));
  }

  public static InputLanguage toInputLanguage(String language) {
    return InputLanguage.swigToEnum(CVC4JNI.toInputLanguage__SWIG_1(language));
  }

  public static OutputLanguage toOutputLanguage(String language) {
    return OutputLanguage.swigToEnum(CVC4JNI.toOutputLanguage__SWIG_1(language));
  }

  public static java.math.BigInteger fnv1a_64(java.math.BigInteger v, java.math.BigInteger hash) {
    return CVC4JNI.fnv1a_64__SWIG_0(v, hash);
  }

  public static java.math.BigInteger fnv1a_64(java.math.BigInteger v) {
    return CVC4JNI.fnv1a_64__SWIG_1(v);
  }

  public static boolean isAssociative(Kind k) {
    return CVC4JNI.isAssociative(k.swigValue());
  }

  public static String kindToString(Kind k) {
    return CVC4JNI.kindToString(k.swigValue());
  }

  public static TheoryId getTHEORY_FIRST() {
    return TheoryId.swigToEnum(CVC4JNI.THEORY_FIRST_get());
  }

  public static TheoryId getTHEORY_SAT_SOLVER() {
    return TheoryId.swigToEnum(CVC4JNI.THEORY_SAT_SOLVER_get());
  }

  public static TheoryId kindToTheoryId(Kind k) {
    return TheoryId.swigToEnum(CVC4JNI.kindToTheoryId(k.swigValue()));
  }

  public static TheoryId typeConstantToTheoryId(TypeConstant typeConstant) {
    return TheoryId.swigToEnum(CVC4JNI.typeConstantToTheoryId(typeConstant.swigValue()));
  }

  public static String getStatsPrefix(TheoryId theoryId) {
    return CVC4JNI.getStatsPrefix(theoryId.swigValue());
  }

  public static Object mkRef(Object arg0) {
    return CVC4JNI.mkRef(arg0);
  }

  public static void dlRef(Object arg0) {
    CVC4JNI.dlRef(arg0);
  }

}
