/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class DatatypeConstructorArg {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DatatypeConstructorArg(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DatatypeConstructorArg obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_DatatypeConstructorArg(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getName() {
    return CVC4JNI.DatatypeConstructorArg_getName(swigCPtr, this);
  }

  public Expr getSelector() {
    return new Expr(CVC4JNI.DatatypeConstructorArg_getSelector(swigCPtr, this), true);
  }

  public Expr getConstructor() {
    return new Expr(CVC4JNI.DatatypeConstructorArg_getConstructor(swigCPtr, this), true);
  }

  public SelectorType getType() {
    return new SelectorType(CVC4JNI.DatatypeConstructorArg_getType(swigCPtr, this), true);
  }

  public Type getRangeType() {
    return new Type(CVC4JNI.DatatypeConstructorArg_getRangeType(swigCPtr, this), true);
  }

  public boolean isResolved() {
    return CVC4JNI.DatatypeConstructorArg_isResolved(swigCPtr, this);
  }

  public void toStream(java.io.OutputStream out) {
    edu.nyu.acsys.CVC4.JavaOutputStreamAdapter tempout = new edu.nyu.acsys.CVC4.JavaOutputStreamAdapter();
    try {
      CVC4JNI.DatatypeConstructorArg_toStream(swigCPtr, this, edu.nyu.acsys.CVC4.JavaOutputStreamAdapter.getCPtr(tempout));
    } finally {
    new java.io.PrintStream(out).print(tempout.toString());
    }
  }

  public String toString() {
    return CVC4JNI.DatatypeConstructorArg_toString(swigCPtr, this);
  }

}
