/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class DeclareSygusPrimedVarCommand extends DeclarationDefinitionCommand {
  private transient long swigCPtr;

  protected DeclareSygusPrimedVarCommand(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.DeclareSygusPrimedVarCommand_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DeclareSygusPrimedVarCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_DeclareSygusPrimedVarCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DeclareSygusPrimedVarCommand(String id, Type type) {
    this(CVC4JNI.new_DeclareSygusPrimedVarCommand(id, Type.getCPtr(type), type), true);
  }

  public Type getType() {
    return new Type(CVC4JNI.DeclareSygusPrimedVarCommand_getType(swigCPtr, this), true);
  }

  public void invoke(SmtEngine smtEngine) {
    CVC4JNI.DeclareSygusPrimedVarCommand_invoke(swigCPtr, this, SmtEngine.getCPtr(smtEngine), smtEngine);
  }

  public Command exportTo(ExprManager exprManager, ExprManagerMapCollection variableMap) {
    long cPtr = CVC4JNI.DeclareSygusPrimedVarCommand_exportTo(swigCPtr, this, ExprManager.getCPtr(exprManager), exprManager, ExprManagerMapCollection.getCPtr(variableMap), variableMap);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

  public Command clone() {
    long cPtr = CVC4JNI.DeclareSygusPrimedVarCommand_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

  public String getCommandName() {
    return CVC4JNI.DeclareSygusPrimedVarCommand_getCommandName(swigCPtr, this);
  }

}
