/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class DefineFunctionCommand extends DeclarationDefinitionCommand {
  private transient long swigCPtr;

  protected DefineFunctionCommand(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.DefineFunctionCommand_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DefineFunctionCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_DefineFunctionCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DefineFunctionCommand(String id, Expr func, Expr formula) {
    this(CVC4JNI.new_DefineFunctionCommand__SWIG_0(id, Expr.getCPtr(func), func, Expr.getCPtr(formula), formula), true);
  }

  public DefineFunctionCommand(String id, Expr func, vectorExpr formals, Expr formula) {
    this(CVC4JNI.new_DefineFunctionCommand__SWIG_1(id, Expr.getCPtr(func), func, vectorExpr.getCPtr(formals), formals, Expr.getCPtr(formula), formula), true);
  }

  public Expr getFunction() {
    return new Expr(CVC4JNI.DefineFunctionCommand_getFunction(swigCPtr, this), true);
  }

  public vectorExpr getFormals() {
    return new vectorExpr(CVC4JNI.DefineFunctionCommand_getFormals(swigCPtr, this), false);
  }

  public Expr getFormula() {
    return new Expr(CVC4JNI.DefineFunctionCommand_getFormula(swigCPtr, this), true);
  }

  public void invoke(SmtEngine smtEngine) {
    CVC4JNI.DefineFunctionCommand_invoke(swigCPtr, this, SmtEngine.getCPtr(smtEngine), smtEngine);
  }

  public Command exportTo(ExprManager exprManager, ExprManagerMapCollection variableMap) {
    long cPtr = CVC4JNI.DefineFunctionCommand_exportTo(swigCPtr, this, ExprManager.getCPtr(exprManager), exprManager, ExprManagerMapCollection.getCPtr(variableMap), variableMap);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

  public Command clone() {
    long cPtr = CVC4JNI.DefineFunctionCommand_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

  public String getCommandName() {
    return CVC4JNI.DefineFunctionCommand_getCommandName(swigCPtr, this);
  }

}
