/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public final class InputLanguage {
  public final static InputLanguage INPUT_LANG_AUTO = new InputLanguage("INPUT_LANG_AUTO", CVC4JNI.INPUT_LANG_AUTO_get());
  public final static InputLanguage INPUT_LANG_SMTLIB_V1 = new InputLanguage("INPUT_LANG_SMTLIB_V1", CVC4JNI.INPUT_LANG_SMTLIB_V1_get());
  public final static InputLanguage INPUT_LANG_SMTLIB_V2_0 = new InputLanguage("INPUT_LANG_SMTLIB_V2_0");
  public final static InputLanguage INPUT_LANG_SMTLIB_V2_5 = new InputLanguage("INPUT_LANG_SMTLIB_V2_5");
  public final static InputLanguage INPUT_LANG_SMTLIB_V2_6 = new InputLanguage("INPUT_LANG_SMTLIB_V2_6");
  public final static InputLanguage INPUT_LANG_SMTLIB_V2 = new InputLanguage("INPUT_LANG_SMTLIB_V2", CVC4JNI.INPUT_LANG_SMTLIB_V2_get());
  public final static InputLanguage INPUT_LANG_SMTLIB_V2_6_1 = new InputLanguage("INPUT_LANG_SMTLIB_V2_6_1");
  public final static InputLanguage INPUT_LANG_TPTP = new InputLanguage("INPUT_LANG_TPTP");
  public final static InputLanguage INPUT_LANG_CVC4 = new InputLanguage("INPUT_LANG_CVC4");
  public final static InputLanguage INPUT_LANG_Z3STR = new InputLanguage("INPUT_LANG_Z3STR");
  public final static InputLanguage INPUT_LANG_SYGUS = new InputLanguage("INPUT_LANG_SYGUS");
  public final static InputLanguage INPUT_LANG_MAX = new InputLanguage("INPUT_LANG_MAX");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static InputLanguage swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + InputLanguage.class + " with value " + swigValue);
  }

  private InputLanguage(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private InputLanguage(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private InputLanguage(String swigName, InputLanguage swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static InputLanguage[] swigValues = { INPUT_LANG_AUTO, INPUT_LANG_SMTLIB_V1, INPUT_LANG_SMTLIB_V2_0, INPUT_LANG_SMTLIB_V2_5, INPUT_LANG_SMTLIB_V2_6, INPUT_LANG_SMTLIB_V2, INPUT_LANG_SMTLIB_V2_6_1, INPUT_LANG_TPTP, INPUT_LANG_CVC4, INPUT_LANG_Z3STR, INPUT_LANG_SYGUS, INPUT_LANG_MAX };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

