/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class Record {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Record(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Record obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_Record(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Record(vectorPairStringType fields) {
    this(CVC4JNI.new_Record__SWIG_0(vectorPairStringType.getCPtr(fields), fields), true);
  }

  public Record(Record other) {
    this(CVC4JNI.new_Record__SWIG_1(Record.getCPtr(other), other), true);
  }

  public boolean contains(String name) {
    return CVC4JNI.Record_contains(swigCPtr, this, name);
  }

  public long getIndex(String name) {
    return CVC4JNI.Record_getIndex(swigCPtr, this, name);
  }

  public long getNumFields() {
    return CVC4JNI.Record_getNumFields(swigCPtr, this);
  }

  public vectorPairStringType getFields() {
    return new vectorPairStringType(CVC4JNI.Record_getFields(swigCPtr, this), false);
  }

  public pairStringType getField(long index) {
    return new pairStringType(CVC4JNI.Record_getField(swigCPtr, this, index), false);
  }

  public boolean equals(Record r) {
    return CVC4JNI.Record_equals(swigCPtr, this, Record.getCPtr(r), r);
  }

}
