/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class ResourceManager {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ResourceManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ResourceManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_ResourceManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ResourceManager() {
    this(CVC4JNI.new_ResourceManager(), true);
  }

  public boolean limitOn() {
    return CVC4JNI.ResourceManager_limitOn(swigCPtr, this);
  }

  public boolean cumulativeLimitOn() {
    return CVC4JNI.ResourceManager_cumulativeLimitOn(swigCPtr, this);
  }

  public boolean perCallLimitOn() {
    return CVC4JNI.ResourceManager_perCallLimitOn(swigCPtr, this);
  }

  public boolean outOfResources() {
    return CVC4JNI.ResourceManager_outOfResources(swigCPtr, this);
  }

  public boolean outOfTime() {
    return CVC4JNI.ResourceManager_outOfTime(swigCPtr, this);
  }

  public boolean out() {
    return CVC4JNI.ResourceManager_out(swigCPtr, this);
  }

  public java.math.BigInteger getResourceUsage() {
    return CVC4JNI.ResourceManager_getResourceUsage(swigCPtr, this);
  }

  public java.math.BigInteger getTimeUsage() {
    return CVC4JNI.ResourceManager_getTimeUsage(swigCPtr, this);
  }

  public java.math.BigInteger getResourceRemaining() {
    return CVC4JNI.ResourceManager_getResourceRemaining(swigCPtr, this);
  }

  public java.math.BigInteger getTimeRemaining() {
    return CVC4JNI.ResourceManager_getTimeRemaining(swigCPtr, this);
  }

  public java.math.BigInteger getResourceBudgetForThisCall() {
    return CVC4JNI.ResourceManager_getResourceBudgetForThisCall(swigCPtr, this);
  }

  public void spendResource(long amount) {
    CVC4JNI.ResourceManager_spendResource(swigCPtr, this, amount);
  }

  public void setHardLimit(boolean value) {
    CVC4JNI.ResourceManager_setHardLimit(swigCPtr, this, value);
  }

  public void setResourceLimit(java.math.BigInteger units, boolean cumulative) {
    CVC4JNI.ResourceManager_setResourceLimit__SWIG_0(swigCPtr, this, units, cumulative);
  }

  public void setResourceLimit(java.math.BigInteger units) {
    CVC4JNI.ResourceManager_setResourceLimit__SWIG_1(swigCPtr, this, units);
  }

  public void setTimeLimit(java.math.BigInteger millis, boolean cumulative) {
    CVC4JNI.ResourceManager_setTimeLimit__SWIG_0(swigCPtr, this, millis, cumulative);
  }

  public void setTimeLimit(java.math.BigInteger millis) {
    CVC4JNI.ResourceManager_setTimeLimit__SWIG_1(swigCPtr, this, millis);
  }

  public void useCPUTime(boolean cpu) {
    CVC4JNI.ResourceManager_useCPUTime(swigCPtr, this, cpu);
  }

  public void enable(boolean on) {
    CVC4JNI.ResourceManager_enable(swigCPtr, this, on);
  }

  public void beginCall() {
    CVC4JNI.ResourceManager_beginCall(swigCPtr, this);
  }

  public void endCall() {
    CVC4JNI.ResourceManager_endCall(swigCPtr, this);
  }

  public static java.math.BigInteger getFrequencyCount() {
    return CVC4JNI.ResourceManager_getFrequencyCount();
  }

  public SWIGTYPE_p_ListenerCollection__Registration registerHardListener(SWIGTYPE_p_Listener listener) {
    long cPtr = CVC4JNI.ResourceManager_registerHardListener(swigCPtr, this, SWIGTYPE_p_Listener.getCPtr(listener));
    return (cPtr == 0) ? null : new SWIGTYPE_p_ListenerCollection__Registration(cPtr, false);
  }

  public SWIGTYPE_p_ListenerCollection__Registration registerSoftListener(SWIGTYPE_p_Listener listener) {
    long cPtr = CVC4JNI.ResourceManager_registerSoftListener(swigCPtr, this, SWIGTYPE_p_Listener.getCPtr(listener));
    return (cPtr == 0) ? null : new SWIGTYPE_p_ListenerCollection__Registration(cPtr, false);
  }

}
