/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class SygusInvConstraintCommand extends Command {
  private transient long swigCPtr;

  protected SygusInvConstraintCommand(long cPtr, boolean cMemoryOwn) {
    super(CVC4JNI.SygusInvConstraintCommand_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SygusInvConstraintCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_SygusInvConstraintCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SygusInvConstraintCommand(vectorExpr predicates) {
    this(CVC4JNI.new_SygusInvConstraintCommand__SWIG_0(vectorExpr.getCPtr(predicates), predicates), true);
  }

  public SygusInvConstraintCommand(Expr inv, Expr pre, Expr trans, Expr post) {
    this(CVC4JNI.new_SygusInvConstraintCommand__SWIG_1(Expr.getCPtr(inv), inv, Expr.getCPtr(pre), pre, Expr.getCPtr(trans), trans, Expr.getCPtr(post), post), true);
  }

  public vectorExpr getPredicates() {
    return new vectorExpr(CVC4JNI.SygusInvConstraintCommand_getPredicates(swigCPtr, this), false);
  }

  public void invoke(SmtEngine smtEngine) {
    CVC4JNI.SygusInvConstraintCommand_invoke(swigCPtr, this, SmtEngine.getCPtr(smtEngine), smtEngine);
  }

  public Command exportTo(ExprManager exprManager, ExprManagerMapCollection variableMap) {
    long cPtr = CVC4JNI.SygusInvConstraintCommand_exportTo(swigCPtr, this, ExprManager.getCPtr(exprManager), exprManager, ExprManagerMapCollection.getCPtr(variableMap), variableMap);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

  public Command clone() {
    long cPtr = CVC4JNI.SygusInvConstraintCommand_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Command(cPtr, false);
  }

  public String getCommandName() {
    return CVC4JNI.SygusInvConstraintCommand_getCommandName(swigCPtr, this);
  }

}
