/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.nyu.acsys.CVC4;

public class Timer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Timer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Timer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* protected void finalize() {
    delete();
  } */

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CVC4JNI.delete_Timer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Timer() {
    this(CVC4JNI.new_Timer(), true);
  }

  public boolean on() {
    return CVC4JNI.Timer_on(swigCPtr, this);
  }

  public void set(java.math.BigInteger millis, boolean wall_time) {
    CVC4JNI.Timer_set__SWIG_0(swigCPtr, this, millis, wall_time);
  }

  public void set(java.math.BigInteger millis) {
    CVC4JNI.Timer_set__SWIG_1(swigCPtr, this, millis);
  }

  public java.math.BigInteger elapsed() {
    return CVC4JNI.Timer_elapsed(swigCPtr, this);
  }

  public boolean expired() {
    return CVC4JNI.Timer_expired(swigCPtr, this);
  }

}
